[package]
name = "t5fastcam"
version = "0.1.0"
edition = "2021"

[package.metadata.android.sdk]
min_sdk_version = 31
target_sdk_version = 31
max_sdk_version = 33

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.7.0"

